config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :rates
  resources :store_books
  resources :books
  resources :social_links
  resources :addresses
  resources :stores
  resources :genres
  resources :authors
  devise_for :owners
  devise_for :users
  root to: 'home#index'
  get 'home', to: 'home#index', as: 'welcome_index'
  get 'api', to: 'end_points#index', as: 'api'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :store
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre

  has_many_attached :covers

  has_many :rates
  has_many :reviews
  has_many :social_links
  has_many :stores, through: :social_links
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar

  has_one :store
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/social_link.rb
class SocialLink < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :owner

  has_one_attached :logo

  has_many :addresses
  has_many :social_links
  has_many :books, through: :social_links
end

app/models/store_book.rb
class StoreBook < ApplicationRecord
  belongs_to :store
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :rates
  has_many :reviews
end

app/controllers/social_links_controller.rb
class SocialLinksController < ApplicationController
  before_action :set_social_link, only: [:show, :edit, :update, :destroy]

  # GET /social_links
  # GET /social_links.json
  def index
    @social_links = SocialLink.all
  end

  # GET /social_links/1
  # GET /social_links/1.json
  def show
  end

  # GET /social_links/new
  def new
    @social_link = SocialLink.new
  end

  # GET /social_links/1/edit
  def edit
  end

  # POST /social_links
  # POST /social_links.json
  def create
    @social_link = SocialLink.new(social_link_params)

    respond_to do |format|
      if @social_link.save
        format.html { redirect_to @social_link, notice: 'Social link was successfully created.' }
        format.json { render :show, status: :created, location: @social_link }
      else
        format.html { render :new }
        format.json { render json: @social_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /social_links/1
  # PATCH/PUT /social_links/1.json
  def update
    respond_to do |format|
      if @social_link.update(social_link_params)
        format.html { redirect_to @social_link, notice: 'Social link was successfully updated.' }
        format.json { render :show, status: :ok, location: @social_link }
      else
        format.html { render :edit }
        format.json { render json: @social_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /social_links/1
  # DELETE /social_links/1.json
  def destroy
    @social_link.destroy
    respond_to do |format|
      format.html { redirect_to social_links_url, notice: 'Social link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_social_link
      @social_link = SocialLink.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def social_link_params
      params.require(:social_link).permit(:site, :link, :store_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/end_points_helper.rb
module EndPointsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/social_links_helper.rb
module SocialLinksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/social_links/_form.html.erb
<%= form_with(model: social_link, local: true) do |form| %>
  <% if social_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(social_link.errors.count, "error") %> prohibited this social_link from being saved:</h2>

      <ul>
        <% social_link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :site %>
    <%= form.text_field :site %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.text_field :store_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/social_links/edit.html.erb
<h1 id="hd">Editing Social Link</h1>

<%= render 'form', social_link: @social_link %>

<%= link_to 'Show', @social_link %> |
<%= link_to 'Back', social_links_path %>

app/views/social_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="hd">Social Links</h1>

<table id="tbl">
  <thead>
    <tr>
      <th>Site</th>
      <th>Link</th>
      <th>Store</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @social_links.each do |social_link| %>
      <tr>
        <td><%= social_link.site %></td>
        <td><%= social_link.link %></td>
        <td><%= social_link.store_id %></td>
        <td><%= link_to 'Show', social_link %></td>
        <td><%= link_to 'Edit', edit_social_link_path(social_link) %></td>
        <td><%= link_to 'Destroy', social_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table id="tbl">

<br>

<%= link_to 'New Social Link', new_social_link_path %>

app/views/social_links/new.html.erb
<h1 id="hd">New Social Link</h1>

<%= render 'form', social_link: @social_link %>

<%= link_to 'Back', social_links_path %>

app/views/social_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @social_link.site %>
</p>

<p>
  <strong>Link:</strong>
  <%= @social_link.link %>
</p>

<p>
  <strong>Store:</strong>
  <%= @social_link.store_id %>
</p>

<%= link_to 'Edit', edit_social_link_path(@social_link) %> |
<%= link_to 'Back', social_links_path %>