config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :rates
  resources :store_books
  resources :books
  resources :social_links
  resources :addresses
  resources :stores
  resources :genres
  resources :authors
  devise_for :owners
  devise_for :users
  root to: 'home#index'
  get 'home', to: 'home#index', as: 'welcome_index'
  get 'api', to: 'end_points#index', as: 'api'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :store
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre

  has_many_attached :covers

  has_many :rates
  has_many :reviews
  has_many :social_links
  has_many :stores, through: :social_links
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar

  has_one :store
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/social_link.rb
class SocialLink < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :owner

  has_one_attached :logo

  has_many :addresses
  has_many :social_links
  has_many :books, through: :social_links
end

app/models/store_book.rb
class StoreBook < ApplicationRecord
  belongs_to :store
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :rates
  has_many :reviews
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :about, :phone, :owner_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/end_points_helper.rb
module EndPointsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.text_field :owner_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1 id="hd">Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="hd">Stores</h1>

<table id="tbl">
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Phone</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.about %></td>
        <td><%= store.phone %></td>
        <td><%= store.owner_id %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table id="tbl">

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1 id="hd">New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @store.about %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @store.owner_id %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>