config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :rates
  resources :store_books
  resources :books
  resources :social_links
  resources :addresses
  resources :stores
  resources :genres
  resources :authors
  devise_for :owners
  devise_for :users
  root to: 'home#index'
  get 'home', to: 'home#index', as: 'welcome_index'
  get 'api', to: 'end_points#index', as: 'api'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :store
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre

  has_many_attached :covers

  has_many :rates
  has_many :reviews
  has_many :social_links
  has_many :stores, through: :social_links
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :avatar

  has_one :store
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/social_link.rb
class SocialLink < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :owner

  has_one_attached :logo

  has_many :addresses
  has_many :social_links
  has_many :books, through: :social_links
end

app/models/store_book.rb
class StoreBook < ApplicationRecord
  belongs_to :store
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  has_many :rates
  has_many :reviews
end

app/controllers/store_books_controller.rb
class StoreBooksController < ApplicationController
  before_action :set_store_book, only: [:show, :edit, :update, :destroy]

  # GET /store_books
  # GET /store_books.json
  def index
    @store_books = StoreBook.all
  end

  # GET /store_books/1
  # GET /store_books/1.json
  def show
  end

  # GET /store_books/new
  def new
    @store_book = StoreBook.new
  end

  # GET /store_books/1/edit
  def edit
  end

  # POST /store_books
  # POST /store_books.json
  def create
    @store_book = StoreBook.new(store_book_params)

    respond_to do |format|
      if @store_book.save
        format.html { redirect_to @store_book, notice: 'Store book was successfully created.' }
        format.json { render :show, status: :created, location: @store_book }
      else
        format.html { render :new }
        format.json { render json: @store_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_books/1
  # PATCH/PUT /store_books/1.json
  def update
    respond_to do |format|
      if @store_book.update(store_book_params)
        format.html { redirect_to @store_book, notice: 'Store book was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_book }
      else
        format.html { render :edit }
        format.json { render json: @store_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_books/1
  # DELETE /store_books/1.json
  def destroy
    @store_book.destroy
    respond_to do |format|
      format.html { redirect_to store_books_url, notice: 'Store book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_book
      @store_book = StoreBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_book_params
      params.require(:store_book).permit(:edition, :price, :is_available, :store_id, :book_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/end_points_helper.rb
module EndPointsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/store_books_helper.rb
module StoreBooksHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/store_books/_form.html.erb
<%= form_with(model: store_book, local: true) do |form| %>
  <% if store_book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store_book.errors.count, "error") %> prohibited this store_book from being saved:</h2>

      <ul>
        <% store_book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :edition %>
    <%= form.text_field :edition %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :is_available %>
    <%= form.check_box :is_available %>
  </div>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.text_field :store_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/store_books/edit.html.erb
<h1 id="hd">Editing Store Book</h1>

<%= render 'form', store_book: @store_book %>

<%= link_to 'Show', @store_book %> |
<%= link_to 'Back', store_books_path %>

app/views/store_books/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="hd">Store Books</h1>

<table id="tbl">
  <thead>
    <tr>
      <th>Edition</th>
      <th>Price</th>
      <th>Is available</th>
      <th>Store</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @store_books.each do |store_book| %>
      <tr>
        <td><%= store_book.edition %></td>
        <td><%= store_book.price %></td>
        <td><%= store_book.is_available %></td>
        <td><%= store_book.store_id %></td>
        <td><%= store_book.book_id %></td>
        <td><%= link_to 'Show', store_book %></td>
        <td><%= link_to 'Edit', edit_store_book_path(store_book) %></td>
        <td><%= link_to 'Destroy', store_book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table id="tbl">

<br>

<%= link_to 'New Store Book', new_store_book_path %>

app/views/store_books/new.html.erb
<h1 id="hd">New Store Book</h1>

<%= render 'form', store_book: @store_book %>

<%= link_to 'Back', store_books_path %>

app/views/store_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edition:</strong>
  <%= @store_book.edition %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store_book.price %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @store_book.is_available %>
</p>

<p>
  <strong>Store:</strong>
  <%= @store_book.store_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @store_book.book_id %>
</p>

<%= link_to 'Edit', edit_store_book_path(@store_book) %> |
<%= link_to 'Back', store_books_path %>